# Generated by Django 3.0.5 on 2020-05-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200504_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
